#ifndef __INSSHADER_CONSTANTS_H__
#define __INSSHADER_CONSTANTS_H__

#ifdef _WIN32
#pragma once
#endif

enum {
    SHADER_SPECIFIC_CONST_0 = 38,
    SHADER_SPECIFIC_CONST_1,
    SHADER_SPECIFIC_CONST_2,
    SHADER_SPECIFIC_CONST_3,
    SHADER_SPECIFIC_CONST_4,
    SHADER_SPECIFIC_CONST_5,
    SHADER_SPECIFIC_CONST_6,
    SHADER_SPECIFIC_CONST_7,
    SHADER_SPECIFIC_CONST_8,
    SHADER_SPECIFIC_CONST_9
};

#endif